mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi

model:
  path: ssdlite_mobilenet_v2
  labelmap_path: coco_91cl_bkgr.txt
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr

detectors:
  ov:
    type: openvino
    device: GPU

go2rtc:
  streams:
    doorbell_1:
      - rtsp://admin:July122010@192.168.40.100:554/h264Preview_01_main
      - ffmpeg:doorbell_1#audio=opus
    doorbell_2:
      - rtsp://admin:July122010@192.168.40.100:554/h264Preview_01_sub

cameras:
  doorbell:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell_1
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/doorbell_2
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    objects:
      track:
        - person

record:
  enabled: true
  retain:
    days: 30
    mode: all

version: 0.17
